name       : xxhash
version    : 0.8.0
release    : 7
source     :
    - https://github.com/Cyan4973/xxHash/archive/v0.8.0.tar.gz : 7054c3ebd169c97b64a92d7b994ab63c70dd53a06974f1f630ab782c28db0f4f
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
component  : programming.library
summary    : Extremely fast hash algorithm
description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It successfully completes the SMHasher test suite which evaluates collision, dispersion and randomness qualities of hash functions. Code is highly portable, and hashes are identical on all platforms (little / big endian).
avx2       : yes
build      : |
    if [[ ! -z "${AVX2BUILD}" ]]; then
      XXH_AVX2=1 DISPATCH=1 %make
    else
      XXH_SSE2=1 DISPATCH=1 %make
    fi
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm $installdir/%libdir%/libxxhash.a
