name       : xxhash
version    : 0.6.5
release    : 1
source     :
    - https://github.com/Cyan4973/xxHash/archive/v0.6.5.tar.gz : 19030315f4fc1b4b2cdb9d7a317069a109f90e39d1fe4c9159b7aaa39030eb95
license    : BSD-2-Clause
component  : programming.library
summary    : Extremely fast hash algorithm
description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It successfully completes the SMHasher test suite which evaluates collision, dispersion and randomness qualities of hash functions. Code is highly portable, and hashes are identical on all platforms (little / big endian).
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm $installdir/%libdir%/libxxhash.a