name       : xxhash
version    : 0.7.4
release    : 5
source     :
    - https://github.com/Cyan4973/xxHash/archive/v0.7.4.tar.gz : 4d9706c9da4fbdf901598f5e3b71db0eddd4ac962e827a73ebf75d66dfd820fe
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
component  : programming.library
summary    : Extremely fast hash algorithm
description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It successfully completes the SMHasher test suite which evaluates collision, dispersion and randomness qualities of hash functions. Code is highly portable, and hashes are identical on all platforms (little / big endian).
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm $installdir/%libdir%/libxxhash.a
